version: '2.1' # specify docker-compose version
# Define the services/containers to be run
services:
  backend: #name of the service
    build: ./api
    image: graphql-api
    container_name: graphql-api
    environment:
      - DATABASE_HOST=database # Dirección base de datos (url o nombre contenedor)
      - DATABASE_NAME=graphqlexample # Nombre base de datos
      - DATABASE_USER=root # Usuario base de datos
      - DATABASE_PASSW=12345 # Passw base de datos
      - DATABASE_DIALECT=mysql
    ports:
      - "4000:4000" #specify ports forewarding
    restart: always
    depends_on:
      database:
        condition: service_healthy
  database: # name of the service
    build: ./database
    image: graphql-database
    container_name: graphql-database
    volumes:
      - ./database/user-recipes-example.sql:/docker-entrypoint-initdb.d/user-recipes-example.sql
      - ./database/data-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=graphqlexample # Nombre base datos
      - MYSQL_ROOT_PASSWORD=12345 # Passw base datos
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 20
